### ISSUE TITLE
模型在mvtec标准数据集上训练，可以问一下为什么效果不好吗？有什么解决方案吗？

### ISSUE THREAD

**Issue by joinusers** [DonaldRR/SimpleNet#32]
(SimpleNet) bash run.sh     #开始train
INFO:__main__:Command line arguments: main.py --gpu 0 --seed 0 --log_group simplenet_mvtec --log_project MVTecAD_Results --results_path results --run_name firstone net -b wideresnet50 -le layer2 -le layer3 --pretrain_embed_dimension 1536 --target_embed_dimension 1536 --patchsize 3 --meta_epochs 40 --embedding_size 256 --gan_epochs 50 --noise_std 0.015 --dsc_hidden 1024 --dsc_layers 2 --dsc_margin .5 --pre_proj 1 dataset --batch_size 2 --resize 329 --imagesize 288 -d toothbrush mvtec DataHere   #命令行参数
INFO:__main__:Dataset: train=60 test=42     #训练集(60good)、测试集(12good，30fefective)
INFO:__main__:Evaluating dataset [mvtec_toothbrush] (1/1)...   #训练单类别数据集“牙刷”
/home/jovyan/anaconda3/envs/SimpleNet/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(/home/jovyan/anaconda3/envs/SimpleNet/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=Wide_ResNet50_2_Weights.IMAGENET1K_V1`. You can also use `weights=Wide_ResNet50_2_Weights.DEFAULT` to get the most up-to-date weights.
warnings.warn(msg)
INFO:__main__:Training models (1/1)         #单类别训练结果
INFO:__main__:instance_auroc（I_auroc): 0.986          #表征图片good/defective分类效果                                                                                 
INFO:__main__:full_pixel_auroc(P_auroc): 0.985          #表征图片分割效果（像素级）

INFO:utils:instance_auroc（I_auroc): 0.986     #多类别平均训练效果
INFO:utils:full_pixel_auroc(P_auroc): 0.985

使用相同的命令行参数，选择test模式：
INFO:__main__:instance_auroc（I_auroc): 0.508
INFO:__main__:full_pixel_auroc(P_auroc): 0.383
<img width="416" alt="image" src="https://github.com/DonaldRR/SimpleNet/assets/114342097/36a2e4ea-f0bc-404c-8b55-1b3a4c5d9b55">

**Comment by Onlydrink** [comment]
你好 方便问一下你这个可视化是怎么展示出来的

**Comment by chenxixxa** [comment]
我也遇到了一样的问题，训练的精度很高有99%，测试的就很低
INFO:utils:instance_auroc: 0.414
INFO:utils:full_pixel_auroc: 0.272
INFO:utils:anomaly_pixel_auroc: 0.229
楼主可以一块讨论下哇
![image](https://github.com/DonaldRR/SimpleNet/assets/102742272/8a42ea36-575e-4ca3-8d59-05945cfb2532)

**Comment by joinusers** [comment]
> 我也遇到了同样的问题，训练的精度有99%，测试的就很低 INFO:utils:instance_auroc: 0.414 INFO:utils:full_pixel_auroc: 0.272 INFO:utils:anomaly_pixel_auroc: 0.229 楼主可以讨论下哇 ![图像](https://user-images.githubusercontent.com/102742272/276586653-8a42ea36-575e-4ca3-8d59-05945cfb2532.png)

好哇，怎么联系你呢

**Comment by chenxixxa** [comment]
> > 我也遇到了同样的问题，训练的精度有99%，测试的就很低 INFO:utils:instance_auroc: 0.414 INFO:utils:full_pixel_auroc: 0.272 INFO:utils:anomaly_pixel_auroc: 0.229 楼主可以讨论下哇 ![图像](https://user-images.githubusercontent.com/102742272/276586653-8a42ea36-575e-4ca3-8d59-05945cfb2532.png)
> 
> 好哇，怎么联系你呢

chenxixxa2023@163.com

**Comment by 456sjd** [comment]
请问下有没有直接训好的模型 我想直接测试下我的数据集

**Comment by Onlydrink** [comment]
> 请问下有没有直接训好的模型 我想直接测试下我的数据集

他给的参数已经训练好较好的效果，你可以直接用你的数据集试一下。
![image](https://github.com/DonaldRR/SimpleNet/assets/55441895/85e2a429-6ab0-4b71-a44e-159c44cb1c96)
这个是他训练的结果

**Comment by nanbowan6662** [comment]
你好，我也遇到了这个问题， 请问你解决了吗

**Comment by rikichou** [comment]
我也复现不了，有已经复现了的朋友吗？

Row Names,instance_auroc,full_pixel_auroc
mvtec_screw,0.5925394548063128,0.5941589700607617
mvtec_pill,0.4162575013638843,0.6108649797694258
mvtec_capsule,0.3382528919026725,0.5600852752470121
mvtec_carpet,0.5325040128410915,0.6535846697401231
mvtec_grid,0.5964912280701754,0.43871774004861214
mvtec_tile,0.6792929292929294,0.3910630009927796
mvtec_wood,0.8342105263157895,0.6367744026677434
mvtec_zipper,0.8353466386554622,0.5154027106212969
mvtec_cable,0.41547976011994003,0.5281190755351722
mvtec_toothbrush,0.5083333333333333,0.3827801596608477
mvtec_transistor,0.5295833333333334,0.4716959814170349
mvtec_metal_nut,0.5796676441837731,0.6306286149491259
mvtec_bottle,0.673015873015873,0.5059354621788167
mvtec_hazelnut,0.7253571428571429,0.6382359505905498
mvtec_leather,0.36888586956521746,0.2398478236301243
Mean,0.5750145426437954,0.5198596544739619

**Comment by joinusers** [comment]
> 我也复现不了，有已经复现了的朋友吗？
> 
> Row Names,instance_auroc,full_pixel_auroc mvtec_screw,0.5925394548063128,0.5941589700607617 mvtec_pill,0.4162575013638843,0.6108649797694258 mvtec_capsule,0.3382528919026725,0.5600852752470121 mvtec_carpet,0.5325040128410915,0.6535846697401231 mvtec_grid,0.5964912280701754,0.43871774004861214 mvtec_tile,0.6792929292929294,0.3910630009927796 mvtec_wood,0.8342105263157895,0.6367744026677434 mvtec_zipper,0.8353466386554622,0.5154027106212969 mvtec_cable,0.41547976011994003,0.5281190755351722 mvtec_toothbrush,0.5083333333333333,0.3827801596608477 mvtec_transistor,0.5295833333333334,0.4716959814170349 mvtec_metal_nut,0.5796676441837731,0.6306286149491259 mvtec_bottle,0.673015873015873,0.5059354621788167 mvtec_hazelnut,0.7253571428571429,0.6382359505905498 mvtec_leather,0.36888586956521746,0.2398478236301243 Mean,0.5750145426437954,0.5198596544739619

可以问一下你训练了多少轮次吗

**Comment by FFFox-abc** [comment]
训练的精度很好99%，测试精度太低了是怎么回事呀

**Comment by JoyWang1123** [comment]
请问您解决了吗 是因为什么呢 为什么训练之后没有权重文件呢(刚入门不是很懂)

**Comment by jssyzsfzy** [comment]
我这边也是 到底啥问题呢

**Comment by Leon-Lee-WC** [comment]
因为因此test里面导入模型的时候有问题，那两个键名和模型名字都有问题

**Comment by jssyzsfzy** [comment]
效果就是不行 换方法了 EfficientAD可以试试 效果不错



在 2023-12-18 16:59:18，"joinusers" ***@***.***> 写道：

Closed #32 as completed.

**Comment by wu33learn** [comment]
> > 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题
> 
> 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
> 
> ```
>  if "pretrained_enc" in state_dicts:
>      self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
>  if "pretrained_dec" in state_dicts:
>      self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
> ```
> 
> 改为：
> 
> ```
> if "discriminator" in state_dicts:
> 	self.discriminator.load_state_dict(state_dicts["discriminator"])
> if "pre_projection" in state_dicts:
> 	self.pre_projection.load_state_dict(state_dicts["pre_projection"])
> ```
> 
> 模型文件名也要保持一致



> > 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题
> 
> 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
> 
> ```
>  if "pretrained_enc" in state_dicts:
>      self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
>  if "pretrained_dec" in state_dicts:
>      self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
> ```
> 
> 改为：
> 
> ```
> if "discriminator" in state_dicts:
> 	self.discriminator.load_state_dict(state_dicts["discriminator"])
> if "pre_projection" in state_dicts:
> 	self.pre_projection.load_state_dict(state_dicts["pre_projection"])
> ```
> 
> 模型文件名也要保持一致

我改了，但是test模式下前后结果一样啊，都非常低

**Comment by wu33learn** [comment]
> 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题

请问你如何修改的，效果很好吗

**Comment by Leon-Lee-WC** [comment]
和论文里面差不多

**Comment by Leon-Lee-WC** [comment]
> > 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题
> 
> 请问你如何修改的，效果很好吗

和论文里面差不多

**Comment by wu33learn** [comment]
> > > 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题
> > 
> > 
> > 请问你如何修改的，效果很好吗
> 
> 和论文里面差不多

我知道为啥了，是那个权重文件加载错了，他源代码simplenet.py的def test 加载路径设置错了，我改过之后，效果挺好的

**Comment by 1s3ss** [comment]
@wu33learn 请问你的加载路径是怎么改的？

**Comment by wu33learn** [comment]
> @wu33learn 请问你的加载路径是怎么改的？

你去看issue的第二个 code erro when test

**Comment by 1s3ss** [comment]
@wu33learn ok，找到了 ，谢谢

**Comment by sdracula** [comment]
> @wu33learn ok，找到了 ，谢谢

请问你现在test效果好吗

**Comment by Cutemoon1** [comment]
@sdracula 还是不行
INFO:utils:instance_auroc : 0.508
INFO:utils:full_pixel_auroc : 0.383

**Comment by wu33learn** [comment]
> > @wu33learn ok，找到了 ，谢谢
> 
> 请问你现在test效果好吗

我没跑mvtec，不知道效果，把路径改下，按理来说test效果应该可以

**Comment by sdracula** [comment]
> > > @wu33learn ok，找到了 ，谢谢
> > 
> > 
> > 请问你现在test效果好吗
> 
> 我没跑mvtec，不知道效果，把路径改下，按理来说test效果应该可以

请问可以看一下你的源码吗，我在训练时三个精度指标都没什么提升，一直是很低

**Comment by sdracula** [comment]
> > > @wu33learn ok，找到了 ，谢谢
> > 
> > 
> > 请问你现在test效果好吗
> 
> 我没跑mvtec，不知道效果，把路径改下，按理来说test效果应该可以

谢谢谢谢

**Comment by sdracula** [comment]
> @sdracula 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0.383

还真是，为什么这么低啊，我改了键值对和路径

**Comment by sdracula** [comment]
> > > @wu33learn ok，找到了 ，谢谢
> > 
> > 
> > 请问你现在test效果好吗
> 
> 我没跑mvtec，不知道效果，把路径改下，按理来说test效果应该可以

请问可以留个联系方式吗

**Comment by sdracula** [comment]
> > > > @wu33learn ok，找到了 ，谢谢
> > > 
> > > 
> > > 请问你现在test效果好吗
> > 
> > 
> > 我没跑mvtec，不知道效果，把路径改下，按理来说test效果应该可以
> 
> 请问可以留个联系方式吗

可以有偿

**Comment by sdracula** [comment]
> @sdracula 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0.383

test or train?

**Comment by sdracula** [comment]
> @sdracula 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0
我现在能复现出来了，之前有点问题也是只有0.5

**Comment by Cutemoon1** [comment]
> > @sdracula 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0
> > 我现在能复现出来了，之前有点问题也是只有0.5

是test，请问你是怎么做出来的？

**Comment by sdracula** [comment]
> > > @sdracula 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0
> > > 我现在能复现出来了，之前有点问题也是只有0.5
> 
> 是test，请问你是怎么做出来的？

可能是测试集的问题，重新解压一下数据集，再试一下

**Comment by kimsax** [comment]
> > > 因为test里面导入模型的时候有问题，那两个键名和模型名字都有问题
> > 
> > 
> > 请问你如何修改的，效果很好吗
> 
> 和论文里面差不多

您好 可以分享一下您的代码，和模型文件吗，我这边一直复现不出来好的效果，谢谢

**Comment by kimsax** [comment]
> > 请问下有没有直接训好的模型 我想直接测试下我的数据集
> 
> 他给的参数已经训练好较好的效果，你可以直接用你的数据集试一下。 ![image](https://private-user-images.githubusercontent.com/55441895/278997204-85e2a429-6ab0-4b71-a44e-159c44cb1c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTA4NDMsIm5iZiI6MTcxMjQ1MDU0MywicGF0aCI6Ii81NTQ0MTg5NS8yNzg5OTcyMDQtODVlMmE0MjktNmFiMC00YjcxLWE0NGUtMTU5YzQ0Y2IxYzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAwNDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYjA1OWZlNjM1ZjJjNjgyYjE5NGU2NDg2NjE0MTU3MTgzNDFjZWY4ZTA4ODM5ZDNkZWRhMWE3OWRlOTY5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMsGyexcXtDEkytTIFbIIIvapbQUqsMXQWd1ZwhZMcY) 这个是他训练的结果
这个库里没有参数文件和模型文件吧，请问你在哪找到的，可以分享一下吗

**Comment by fayeYMO** [comment]
> > > > [@sdracula](https://github.com/sdracula) 还是不行 INFO:utils:instance_auroc : 0.508 INFO:utils:full_pixel_auroc : 0
> > > > 我现在能复现出来了，之前有点问题也是只有0.5
> > 
> > 
> > 是test，请问你是怎么做出来的？
> 
> 可能是测试集的问题，重新解压一下数据集，再试一下


我想问一下这个训练大概要多久啊，用2080来跑的话

**Comment by fayeYMO** [comment]
@Cutemoon1 @wu33learn 请问test模式需要改哪里啊，原代码这里 只有，试着test参数设置默认为true也没用   
```PYTHON  
if not test:
                i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
            else:
                # BUG: the following line is not using. Set test with True by default.
                # i_auroc, p_auroc, pro_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
                print("Warning: Pls set test with true by default")
```

**Comment by fayeYMO** [comment]
> [@Cutemoon1](https://github.com/Cutemoon1) [@wu33learn](https://github.com/wu33learn) 请问test模式需要改哪里啊，原代码这里 只有，试着test参数设置默认为true也没用
> 
> if not test:
>                 i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
>             else:
>                 # BUG: the following line is not using. Set test with True by default.
>                 # i_auroc, p_auroc, pro_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
>                 print("Warning: Pls set test with true by default")

大概做到主楼的效果了，0.5几的指标，大概方法是解除上面的代码注释，除了test参数设置默认为true，还要将save_segmentation_images设为true，并且test函数只返回两个值，所以要把接受的pro_auroc变量移到其他地方

**Comment by wu33learn** [comment]
我记得是那个权重加载错误了啊，就那一个地方错误了吧，你找找，我记得权重名字好像不对或者位置不对












吴国成
***@***.***

郑州大学
学生

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月28日(周五) 晚上11:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DonaldRR/SimpleNet] 模型在mvtec标准数据集上训练，可以问一下为什么效果不好吗？有什么解决方案吗？ (Issue #32)


    
@Cutemoon1 @wu33learn 请问test模式需要改哪里啊，原代码这里 只有，试着test参数设置默认为true也没用
 
if not test:
 i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
 else:
 # BUG: the following line is not using. Set test with True by default.
 # i_auroc, p_auroc, pro_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
 print("Warning: Pls set test with true by default")
  
大概做到主楼的效果了，0.5几的指标，大概方法是解除上面的代码注释，除了test参数设置默认为true，还要将save_segmentation_images设为true，并且test函数只返回两个值，所以要把接受的pro_auroc变量移到其他地方

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  fayeYMO left a comment (DonaldRR/SimpleNet#32)
  
@Cutemoon1 @wu33learn 请问test模式需要改哪里啊，原代码这里 只有，试着test参数设置默认为true也没用
 
if not test:
 i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
 else:
 # BUG: the following line is not using. Set test with True by default.
 # i_auroc, p_auroc, pro_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
 print("Warning: Pls set test with true by default")
  
大概做到主楼的效果了，0.5几的指标，大概方法是解除上面的代码注释，除了test参数设置默认为true，还要将save_segmentation_images设为true，并且test函数只返回两个值，所以要把接受的pro_auroc变量移到其他地方

**Comment by fayeYMO** [comment]
@wu33learn 谢谢你的回复，如果是上面提到的
确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了

 if "pretrained_enc" in state_dicts:
     self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
 if "pretrained_dec" in state_dicts:
     self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
改为：

if "discriminator" in state_dicts:
	self.discriminator.load_state_dict(state_dicts["discriminator"])
if "pre_projection" in state_dicts:
	self.pre_projection.load_state_dict(state_dicts["pre_projection"])

我已经修改过了，确实出来就是0.5多。请问当时你是成功把测试的高指标也复现出来了吗？

**Comment by wu33learn** [comment]
忘了 应该是吧，估计是的 明天我帮你看看，你翻翻其他issue，应该有解决的












吴国成
***@***.***

郑州大学
学生

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月1日(周六) 凌晨0:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DonaldRR/SimpleNet] 模型在mvtec标准数据集上训练，可以问一下为什么效果不好吗？有什么解决方案吗？ (Issue #32)


   
@wu33learn 谢谢你的回复，如果是上面提到的
 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
 
if "pretrained_enc" in state_dicts:
 self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
 if "pretrained_dec" in state_dicts:
 self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
 改为：
 
if "discriminator" in state_dicts:
 self.discriminator.load_state_dict(state_dicts["discriminator"])
 if "pre_projection" in state_dicts:
 self.pre_projection.load_state_dict(state_dicts["pre_projection"])
 
我已经修改过了，确实出来就是0.5多。请问当时你是成功把测试的高指标也复现出来了吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  fayeYMO left a comment (DonaldRR/SimpleNet#32)
 
@wu33learn 谢谢你的回复，如果是上面提到的
 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
 
if "pretrained_enc" in state_dicts:
 self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
 if "pretrained_dec" in state_dicts:
 self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
 改为：
 
if "discriminator" in state_dicts:
 self.discriminator.load_state_dict(state_dicts["discriminator"])
 if "pre_projection" in state_dicts:
 self.pre_projection.load_state_dict(state_dicts["pre_projection"])
 
我已经修改过了，确实出来就是0.5多。请问当时你是成功把测试的高指标也复现出来了吗？

**Comment by wu33learn** [comment]
就改个这就ok了吧，你看看那个是不是最佳的权重啊，别用的前几轮的












吴国成
***@***.***

郑州大学
学生

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月1日(周六) 凌晨0:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DonaldRR/SimpleNet] 模型在mvtec标准数据集上训练，可以问一下为什么效果不好吗？有什么解决方案吗？ (Issue #32)


   
@wu33learn 谢谢你的回复，如果是上面提到的
 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
 
if "pretrained_enc" in state_dicts:
 self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
 if "pretrained_dec" in state_dicts:
 self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
 改为：
 
if "discriminator" in state_dicts:
 self.discriminator.load_state_dict(state_dicts["discriminator"])
 if "pre_projection" in state_dicts:
 self.pre_projection.load_state_dict(state_dicts["pre_projection"])
 
我已经修改过了，确实出来就是0.5多。请问当时你是成功把测试的高指标也复现出来了吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  fayeYMO left a comment (DonaldRR/SimpleNet#32)
 
@wu33learn 谢谢你的回复，如果是上面提到的
 确实如此，train()保存模型和test()加载模型不一致，改一下test()就可以了
 
if "pretrained_enc" in state_dicts:
 self.feature_enc.load_state_dict(state_dicts["pretrained_enc"])
 if "pretrained_dec" in state_dicts:
 self.feature_dec.load_state_dict(state_dicts["pretrained_dec"])
 改为：
 
if "discriminator" in state_dicts:
 self.discriminator.load_state_dict(state_dicts["discriminator"])
 if "pre_projection" in state_dicts:
 self.pre_projection.load_state_dict(state_dicts["pre_projection"])
 
我已经修改过了，确实出来就是0.5多。请问当时你是成功把测试的高指标也复现出来了吗？

**Comment by fayeYMO** [comment]
@wu33learn 谢谢你的帮助，经过你的提醒我发现他的test加载的权重路径貌似有问题,本地训练好的权重是ckpt.pth，我修改了一下，得到的auroc, full_pixel_auroc就是0.9以上了，不过他这个分割图感觉还是不够明显。我再看看
```PYTHON
def test(self, training_data, test_data, save_segmentation_images):

        # ckpt_path = os.path.join(self.ckpt_dir, "models.ckpt")
        ckpt_path = os.path.join(self.ckpt_dir, "ckpt.pth")
```

**Comment by chaoqunWang666** [comment]
> 使用了utils文件定义的可视化函数

请问，具体怎么使用，能教教我嘛

**Comment by lj1231** [comment]
> > 使用了utils文件定义的可视化函数
> 
> 请问，具体怎么使用，能教教我嘛

请问一下，你解决这个问题了吗？

**Comment by fayeYMO** [comment]
> > > 使用了utils文件定义的可视化函数
> > 
> > 
> > 请问，具体怎么使用，能教教我嘛
> 
> 请问一下，你解决这个问题了吗？

解决了，你参考我之前的回复

**Comment by lj1231** [comment]
> > > > 使用了utils文件定义的可视化函数
> > > 
> > > 
> > > 请问，具体怎么使用，能教教我嘛
> > 
> > 
> > 请问一下，你解决这个问题了吗？
> 
> 解决了，你参考我之前的回复

你好，我研究了一下，你解决的问题是将论文中的测试指标复现出来，解决方法是将test方法中的models改成ckpt（保存与加载模型路径有问题）。但是我还没复现到这一步，我不知道如何生成可视化的测试图像。之前看到一个评论说是在evaluate函数中调用save_segmentation_images，然后在这里你前面说的方法是在utils中定义可视化函数。我不太理解，是只要在源码中修改一些参数，然后再次运行main函数，就能生成每个异常图像的检测图；还是要重新写一个test函数？亦或是其他方法？谢谢

**Comment by fayeYMO** [comment]
> 你好，我研究了一下，你解决的问题是将论文中的测试指标复现出来，解决方法是将test方法中的models改成ckpt（保存与加载模型路径有问题）。但是我还没复现到这一步，我不知道如何生成可视化的测试图像。之前看到一个评论说是在evaluate函数中调用save_segmentation_images，然后在这里你前面说的方法是在utils中定义可视化函数。我不太理解，是只要在源码中修改一些参数，然后再次运行main函数，就能生成每个异常图像的检测图；还是要重新写一个test函数？亦或是其他方法？谢谢

“大概方法是解除上面的代码注释，除了test参数设置默认为true，还要将save_segmentation_images设为true，并且test函数只返回两个值，所以要把接受的pro_auroc变量移到其他地方”

**Comment by lj1231** [comment]
> > 你好，我研究了一下，你解决的问题是将论文中的测试指标复现出来，解决方法是将test方法中的models改成ckpt（保存与加载模型路径有问题）。但是我还没复现到这一步，我不知道如何生成可视化的测试图像。之前看到一个评论说是在evaluate函数中调用save_segmentation_images，然后在这里你前面说的方法是在utils中定义可视化函数。我不太理解，是只要在源码中修改一些参数，然后再次运行main函数，就能生成每个异常图像的检测图；还是要重新写一个test函数？亦或是其他方法？谢谢
> 
> “大概方法是解除上面的代码注释，除了test参数设置默认为true，还要将save_segmentation_images设为true，并且test函数只返回两个值，所以要把接受的pro_auroc变量移到其他地方”

请问一下这样改有问题吗？就是在进入判断前将test和save_segmentation_images都设置为true，然后接受test函数返回值的三个参数中，将pro_auroc去掉。那这个pro_auroc设为none吗？不是的话要怎么更新它呢？

修改前：
            if not test:
                i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
            else:
                # BUG: the following line is not using. Set test with True by default.
                # i_auroc, p_auroc, pro_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
                print("Warning: Pls set test with true by default")
修改后:
            test = True# test设置为True
            save_segmentation_images = True#将save_segmentation_images设置为True
            if not test:
                i_auroc, p_auroc, pro_auroc = SimpleNet.train(dataloaders["training"], dataloaders["testing"])
            else:
                # BUG: the following line is not using. Set test with True by default.
                i_auroc, p_auroc =  SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
                print("Warning: Pls set test with true by default")

**Comment by D-IceIce** [comment]
Test部分修改参考，希望能够给大家提供帮助：

1、将[line 291-5297](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L291-L297)改为：
```
  ckpt_path = os.path.join(self.ckpt_dir, "ckpt.pth")
  if os.path.exists(ckpt_path):
      state_dict = torch.load(ckpt_path, map_location=self.device)
      if 'discriminator' in state_dict:
          self.discriminator.load_state_dict(state_dict['discriminator'])
          if "pre_projection" in state_dict:
              self.pre_projection.load_state_dict(state_dict["pre_projection"])
      else:
          self.load_state_dict(state_dict, strict=False)
```
2、将[line 300](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L300)改为
```
scores, segmentations, features, labels_gt, masks_gt = self.predict(test_data)
auroc, full_pixel_auroc, anomaly_pixel_auroc = self._evaluate(test_data, scores, segmentations, features,
                                                                      labels_gt, masks_gt)
```
3、将[line 337-340](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L337-L340)注释掉


**English Version**
Suggested modifications to the `def test()` — hope this helps everyone:

1. Replace [line 291–297](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L291-L297) with:

```
ckpt_path = os.path.join(self.ckpt_dir, "ckpt.pth")
if os.path.exists(ckpt_path):
    state_dict = torch.load(ckpt_path, map_location=self.device)
    if 'discriminator' in state_dict:
        self.discriminator.load_state_dict(state_dict['discriminator'])
        if "pre_projection" in state_dict:
            self.pre_projection.load_state_dict(state_dict["pre_projection"])
    else:
        self.load_state_dict(state_dict, strict=False)
```

2. Replace [line 300](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L300) with:

```
scores, segmentations, features, labels_gt, masks_gt = self.predict(test_data)
auroc, full_pixel_auroc, anomaly_pixel_auroc = self._evaluate(
    test_data, scores, segmentations, features, labels_gt, masks_gt
)
```

3. Comment out [lines 337–340](https://github.com/DonaldRR/SimpleNet/blob/351a2b8d4e8cfc944dbccbf9bc6ceda930c6f26b/simplenet.py#L337-L340).
